name: publish to nuget
env:
  TESTPROJPATH: '.\test\NaturalStringComparerTest'
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, test, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.0.x'
      - run: dotnet restore
      - name: test
        run: dotnet test {{TESTPROJPATH}}
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: .\NaturalStringComparer\NaturalStringComparer.csproj

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          # INCLUDE_SYMBOLS: false
